CoberturasFianzas/Models/ProductosModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Examen.Models
{
    [Serializable()]
    public class ProductosModels
    {
        public int id { get; set; }
        public string Descripcion { get; set; }
        public string Pais { get; set; }

        public int idRamo { get; set; }
    }
}

CoberturasFianzas/Models/ProductosRamosView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Examen.Models
{
    public class ProductosRamosView
    {
        public string claveProducto  { get; set; }
        public string Producto { get; set; }
        public string claveRamo { get; set; }
        public string Ramo { get; set; }
    }
}

CoberturasFianzas/Models/RamosModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Examen.Models
{
    public class RamosModels
    {
        public int id { get; set; }
        public string Descripcion { get; set; }
        public string Pais { get; set; }
    }
}

CoberturasFianzas/Models/UsariosModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Examen.Models
{
    public class UsariosModels
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Pws { get; set; }
        public string Pais { get; set; }
    }
}

CoberturasFianzas/Models/UserPaisModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Examen.Models
{
    public class UserPaisModels
    {
        public int id { get; set; }
        public string pais { get; set; }
        public string Descripcion { get; set; }
    }
}

CoberturasFianzas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Examen.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CoberturasFianzas/Controllers/ProductosController.cs
using Examen.DAO.Productos;
using Examen.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace CoberturasFianzas.Controllers
{
    public class ProductosController : Controller
    {
        // GET: Productos
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Buscar(ProductosModels productosModels)
        {
            try
            {
                string Pais = Session["Pais"].ToString();

                ProductosDao productosDao = new ProductosDao();
                var Producto = (productosDao.Buscar(productosModels.id, productosModels.Descripcion, Pais, productosModels.idRamo));
                
                return Json(Producto, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}

CoberturasFianzas/Controllers/ProductosRamosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Examen.Controllers
{
    public class ProductosRamosController : Controller
    {
        // GET: ProductosRamos
        public ActionResult Index()
        {
            return View();
        }
    }
}

CoberturasFianzas/Controllers/RamosController.cs
using Examen.DAO.Ramos;
using Examen.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Examen.Controllers
{
    public class RamosController : Controller
    {
        // GET: Ramos
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult buscar(RamosModels RamosModels)
        {
            try
            {
                string Pais = string.Empty;
                if (Session["Pais"] != null)
                {
                    Pais = Session["Pais"].ToString();
                }

                //List<RamosModels> lsRamos = new List<RamosModels>();

                RamosDao ramosDao = new RamosDao();
                var lsRamos = ramosDao.Buscar(RamosModels.id, RamosModels.Descripcion, Pais);

                return Json(lsRamos, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}

CoberturasFianzas/Controllers/UsuariosController.cs
using Examen.DAO.Usuarios;
using Examen.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace CoberturasFianzas.Controllers
{
    public class UsuariosController : Controller
    {
        // GET: Usuarios
        public ActionResult Index()
        {
            return View();
        }

        public int Acceso(UsariosModels UsariosModels)
        {
           return VerificarUsuario(UsariosModels.UserName, UsariosModels.Pws);
        }

        public int VerificarUsuario(string userName, string psw)
        {
            try
            {
                int existeUsuario = 0;
                string result = string.Empty;

                UsuariosDao usuariosDao = new UsuariosDao();
                result= usuariosDao.VerificarUsuario(userName, psw);

                if (result != null && result!="")
                {
                       existeUsuario = 1;
                       Session["Pais"] = result;
                }

                return existeUsuario;
            }
            catch (Exception ex)
            {

                throw;
            }
           
        }
    }

}

CoberturasFianzas/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CoberturasFianzas/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CoberturasFianzas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron col-xs-12">
    <div class="center-block">
        <form>
            <div class="container">
                <div clas="form-group">
                    <label for="uname"><b>Username</b></label>
                    <input type="text" placeholder="Usuario" name="usuario" id="txtusuario" required>
                </div>
                <div clas="form-group">
                    <label for="psw"><b>Password</b></label>
                    <input type="password" placeholder="Password" name="psw" id="txtpassword" required>
                </div>
                <div clas="form-group">
                    <input type="button" id="btnlogin" name="btnlogin" value="Ingresar" />
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script>

        var objUser = {
            login: function () {
                $("#btnlogin").click(function () {
                    var usuariosModels2 = {
                        "UserName" :  $("#txtusuario").val(),
                        "Pws"      :  $("#txtpassword").val()
                    };

                    var Data = JSON.stringify(usuariosModels2);

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Acceso", "Usuarios")',
                        data: "{'UsariosModels':" + Data + "}",
                        dataType: "text",
                        contentType: "application/json; charset:utf-8",
                        success: function (response) {
                            var existUsuario = response;

                            if (existUsuario == 1)
                            {
                                window.location.href = '@Url.Action("Index", "ProductosRamos")';
                            }
                            else
                            {
                                window.location.href = '@Url.Action("Index", "Home")';
                                alert("Usuario Incorrecto favor de verificar datos")
                            }
                        },
                        error: function (result) {
                            alert('ERROR' + result.status + '' + result.statusText);
                        }

                    });
                })
            }
        }

        $(document).ready(function () {
                objUser.login();
        });

    </script>
}

@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

CoberturasFianzas/Views/ProductosRamos/Index.cshtml
@model IEnumerable<Examen.Models.ProductosRamosView>

@{
    ViewBag.Title = "Index";
}

<h2>Seleccion Ramos y Productos</h2>

<form>
    <div class="form-group">
        <div class="col">
            @Html.Label("Ramo", "Ramo", new { @class = "btn btn-link", id = "lbRamo" })
        </div>
        <div class="col">
            @Html.TextBox("Ramo", "", new { @class = "form-control", id = "txtRamo" })
        </div>
        <div class="col">
            @Html.Label("", "Descripcion del Ramo", new { id = "lbDescripcion" })
        </div>
    </div>
    <div class="form-group">
        <div class="col">
            @Html.Label("Producto", "Producto", new { @class = "btn btn-link", id = "lbProducto" })
        </div>
        <div class="col">
            @Html.TextBox("Producto", "", new { @class = "form-control", id = "txtProducto" })
        </div>
        <div class="col">
            @Html.Label("", "Descripcion del Producto", new { id = "lbDescripcionProducto" })
        </div>
    </div>
</form>

@Html.Partial("_PartialModalProducto")
@Html.Partial("_PartialModalRamo")


@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/bootbox/bootbox.js"></script>
@section Scripts{
    
    <script>
     var ObjProducto = {
    MostrarModal: function () {
        $("#lbProducto").click(function () {
            var valorRamo = $("#txtRamo").val();
            if (valorRamo === "") {
                bootbox.alert("Favor de Seleccionar un ramo!");
            }
            else {
                $("#ModalProductos").modal("show");
            }
        });
    },
    GetProductos: function (Descripcion, id) {
        $("#txtProducto").val(id);
        $("#lbDescripcionProducto").text(Descripcion);
        $("#ModalProductos").modal("hide");
    },
    Buscar: function () {
        $("#btnBuscarProducto").click(function () {
            var productosModels2 = {
                "id": $("#txtclaveProducto").val(),
                "Descripcion": $("#txtDescripcionProducto").val(),
                "idRamo": $("#txtRamo").val()
            };

            var Data = JSON.stringify(productosModels2);

            $.ajax({
                type: "POST",
                url: '@Url.Action("Buscar", "Productos")',
                data: "{'productosModels':" + Data + "}",
                dataType: "json",
                contentType: "application/json; charset:utf-8",
                success: function (response) {
                    var objproductos = response;

                    if (objproductos == null) {
                        bootbox.alert("La busqueda no obtuvo resultados!");
                    }

                    $('#tablaProductos').empty();

                    $.each(objproductos, function (index) {
                        $("#tablaProductos").append('<tr>' +
                            '<td style="cursor: pointer" "><a href="javascript:ObjProducto.GetProductos(\'' + objproductos[index].Descripcion + '\',\'' + objproductos[index].id + '\')" > ' + objproductos[index].id + '</a></td>' +
                            '<td >' + objproductos[index].Descripcion + '</td>' +
                            '</tr>');
                    });
                },
                error: function (result) {
                    alert('ERROR' + result.status + '' + result.statusText);
                }

            });
        })
    }
}

     var objRamo = {
    MostrarModal: function () {
        $("#lbRamo").click(function () {
            $("#ModalRamos").modal("show");
        });
    },
    Buscar: function () {
        $("#btnBuscarRamo").click(function () {
            var RamosModels2 = {
                "id": $("#txtclaveRamo").val(),
                "Descripcion": $("#txtDescripcionRamo").val()
            };

            var Data = JSON.stringify(RamosModels2);

            $.ajax({
                type: "POST",
                url: '@Url.Action("buscar", "Ramos")',
                data: "{'RamosModels':" + Data + "}",
                dataType: "json",
                contentType: "application/json; charset:utf-8",
                success: function (response) {
                    var objRamos = response;

                    if (objRamos == null) {
                        bootbox.alert("La busqueda no obtuvo resultados!");
                    }

                    $('#tablaRamos').empty();

                    $.each(objRamos, function (index) {
                        $("#tablaRamos").append('<tr>' +
                            '<td style="cursor: pointer" "><a href="javascript:objRamo.GetRamos(\'' + objRamos[index].Descripcion + '\',\'' + objRamos[index].id + '\')" > ' + objRamos[index].id + '</a></td>' +
                            '<td>' + objRamos[index].Descripcion + '</td>' +
                            '</tr>');
                    });

                },
                error: function (result) {
                    alert('ERROR' + result.status + '' + result.statusText);
                }

            });
        })
    },
    GetRamos: function (Descripcion, id) {
        $("#txtRamo").val(id);
        $("#lbDescripcion").text(Descripcion);
        $("#ModalRamos").modal("hide");
    },
}

$(document).ready(function () {
    $("#txtProducto").prop('disabled', true);
    $("#txtRamo").prop('disabled', true);
    ObjProducto.MostrarModal();
    ObjProducto.Buscar();

    objRamo.MostrarModal();
    objRamo.Buscar();
    objRamo.MostrarModal();
});
    </script>
    }

CoberturasFianzas/Views/ProductosRamos/_PartialModalProducto.cshtml
<div id="ModalProductos" class="modal" tabindex="-1" role="dialog"  >
   <div class="modal-dialog" role="document">
       <div class="modal-content">
           <div class="modal-header">
               <h5>Consulta de Productos</h5>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
               </button>
           </div>
           <div class="modal-body">
               <div class="form-group">
                   <label>Clave</label>
                   <input id="txtclaveProducto" name="txtclaveProducto" class="form-control" placeholder="Clave" />
               </div>
               <div class="form-group">
                   <label>Descripcion</label>
                   <input id="txtDescripcionProducto" name="txtDescripcionProducto" class="form-control" placeholder="Clave" />
               </div>
               <div class="table-responsive">
                   <table class="table table-striped table-bordered table-hover">
                       <thead style="background-color: silver">
                           <tr>
                               <td>Clave</td>
                               <td>Descripcion</td>
                           </tr>
                       </thead>
                       <tbody id="tablaProductos">
                       </tbody>
                   </table>
               </div>
           </div>
           <div class="modal-footer">
               <button type="button" class="btn btn-primary" id="btnBuscarProducto">Buscar</button>
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
           </div>
       </div>
   </div>
</div>

CoberturasFianzas/Views/ProductosRamos/_PartialModalRamo.cshtml
<div id="ModalRamos" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog"  role="document">
        <div class="modal-content">
          <div class="modal-header">
              <h5>Consulta de Ramos</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="false">&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <div class="form-group">
                  <label>Clave</label>
                  <input id="txtclaveRamo" name="txtClaveRamo" class="form-control" placeholder="Texto" />
              </div>
              <div class="form-group">
                  <label>Descripcion</label>
                  <input id="txtDescripcionRamo" name="txtxDescripcionRamo" class="form-control" placeholder="Texto" />
              </div>
              <div class="table-responsive">
                  <table class="table table-striped table-bordered table-hover">
                      <thead style="background-color: silver">
                          <tr>
                              <td>Clave</td>
                              <td>Descripcion</td>
                          </tr>
                      </thead>
                      <tbody id="tablaRamos">
                      </tbody>
                  </table>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="btnBuscarRamo">Buscar</button>
          </div>
        </div>
    </div>
</div>

CoberturasFianzas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>